version: "3.7"
services:
  python:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app
    ports:
      - 80:5000
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=setup.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - APP_SETTINGS=app.configs.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgis_example
    networks:
      default:
        aliases:
          - api
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: postgis_example
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 81:8080
    volumes:
      - ./docs/swagger:/usr/share/nginx/html/definitions
    environment:
      API_URL: definitions/swagger.yml
networks:
  default:
