"""Create partner table

Revision ID: 04fc66b5c9ca
Revises:
Create Date: 2020-01-30 04:20:10.393745

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '04fc66b5c9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'partner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('trading_name', sa.String(length=200), nullable=False),
        sa.Column('owner_name', sa.String(length=200), nullable=False),
        sa.Column('document', sa.String(length=100), nullable=False),
        sa.Column('coverage_area', geoalchemy2.types.Geometry(
            geometry_type='MULTIPOLYGON'), nullable=True
        ),
        sa.Column('address', geoalchemy2.types.Geometry(
            geometry_type='POINT'), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('document')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner')
    # ### end Alembic commands ###
